// <auto-generated />
using System;
using GerenciadorProntuarios.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GerenciadorProntuarios.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240225170759_testando")]
    partial class testando
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("GerenciadorProntuarios.Models.Aluno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RG")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("GerenciadorProntuarios.Models.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SgCurso")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("GerenciadorProntuarios.Models.Diploma", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CursoId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CodigoDiploma")
                        .HasColumnType("TEXT");

                    b.Property<int>("CodigoLivro")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoPagina")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataConclusao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataRetirada")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SegundaVia")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoDiplomaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id", "AlunoId", "CursoId");

                    b.HasIndex("TipoDiplomaId");

                    b.ToTable("Diplomas");
                });

            modelBuilder.Entity("GerenciadorProntuarios.Models.Documento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("GerenciadorProntuarios.Models.DocumentoAluno", b =>
                {
                    b.Property<int>("AlunoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DocumentoId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Consta")
                        .HasColumnType("INTEGER");

                    b.HasKey("AlunoId", "DocumentoId");

                    b.ToTable("DocumentosAluno");
                });

            modelBuilder.Entity("GerenciadorProntuarios.Models.Prontuario", b =>
                {
                    b.Property<Guid>("AlunoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CursoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AlunoId", "CursoId");

                    b.ToTable("Prontuarios");
                });

            modelBuilder.Entity("GerenciadorProntuarios.Models.TipoDiploma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TipoDiploma");
                });

            modelBuilder.Entity("GerenciadorProntuarios.Models.Diploma", b =>
                {
                    b.HasOne("GerenciadorProntuarios.Models.TipoDiploma", "TipoDiploma")
                        .WithMany()
                        .HasForeignKey("TipoDiplomaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoDiploma");
                });
#pragma warning restore 612, 618
        }
    }
}
